BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TYPE payment_method_test AS ENUM ('EFECTIVO','TARJETA','TRANSFERENCIA','OTRO');
CREATE TYPE sale_status_test AS ENUM ('PENDIENTE','PAGADA','CANCELADA','DEVUELTA');
CREATE TYPE inventory_movement_type_test AS ENUM ('ENTRADA','VENTA','DEVOLUCION','MERMA','AJUSTE','TRASPASO');

CREATE TABLE products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre text NOT NULL,
  precio_venta numeric(12,2) NOT NULL,
  costo numeric(12,2) NOT NULL DEFAULT 0,
  activo boolean NOT NULL DEFAULT true
);

CREATE TABLE inventory (
  producto_id bigint PRIMARY KEY REFERENCES products(id),
  stock_actual numeric(12,3) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  folio text NOT NULL UNIQUE,
  usuario_id uuid NOT NULL,
  subtotal numeric(12,2) NOT NULL DEFAULT 0,
  total numeric(12,2) NOT NULL DEFAULT 0,
  estado sale_status_test NOT NULL DEFAULT 'PENDIENTE',
  client_request_id uuid UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE sale_details (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id bigint NOT NULL REFERENCES sales(id),
  producto_id bigint REFERENCES products(id),
  cantidad numeric(12,3) NOT NULL,
  precio_unitario numeric(12,2) NOT NULL,
  costo_unitario numeric(12,2) NOT NULL DEFAULT 0,
  descuento numeric(12,2) NOT NULL DEFAULT 0,
  subtotal numeric(12,2) NOT NULL
);

CREATE TABLE sale_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venta_id bigint NOT NULL REFERENCES sales(id),
  metodo payment_method_test NOT NULL,
  monto numeric(12,2) NOT NULL,
  referencia text
);

CREATE TABLE inventory_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id bigint NOT NULL REFERENCES products(id),
  tipo inventory_movement_type_test NOT NULL,
  cantidad numeric(12,3) NOT NULL,
  stock_anterior numeric(12,3) NOT NULL,
  stock_nuevo numeric(12,3) NOT NULL,
  referencia_id bigint,
  usuario_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE OR REPLACE FUNCTION create_pos_sale_test(
  p_user uuid,
  p_items jsonb,
  p_payments jsonb
) RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
  v_sale_id bigint;
  v_product_id bigint;
  v_qty numeric(12,3);
  v_price numeric(12,2);
  v_cost numeric(12,2);
  v_stock numeric(12,3);
  v_line numeric(12,2);
  v_desc numeric(12,2);
  v_subtotal numeric(12,2) := 0;
  v_paid numeric(12,2) := 0;
  v_item jsonb;
  v_folio text;
BEGIN
  IF jsonb_typeof(p_items) <> 'array' OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'EMPTY_CART';
  END IF;

  IF jsonb_typeof(p_payments) <> 'array' OR jsonb_array_length(p_payments) = 0 THEN
    RAISE EXCEPTION 'EMPTY_PAYMENT';
  END IF;

  v_folio := 'TEST-' || to_char(clock_timestamp(),'YYYYMMDDHH24MISSMSUS');
  INSERT INTO sales(folio,usuario_id,estado) VALUES(v_folio,p_user,'PENDIENTE') RETURNING id INTO v_sale_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items) LOOP
    v_product_id := (v_item->>'producto_id')::bigint;
    v_qty := (v_item->>'cantidad')::numeric;
    IF v_qty <= 0 THEN RAISE EXCEPTION 'INVALID_QTY'; END IF;

    SELECT precio_venta,costo INTO v_price,v_cost
    FROM products WHERE id=v_product_id AND activo=true FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;

    SELECT stock_actual INTO v_stock FROM inventory WHERE producto_id=v_product_id FOR UPDATE;
    IF coalesce(v_stock,0) < v_qty THEN RAISE EXCEPTION 'INSUFFICIENT_STOCK'; END IF;

    v_desc := coalesce((v_item->>'descuento')::numeric,0);
    v_line := round((v_qty*v_price)-v_desc,2);
    IF v_line < 0 THEN RAISE EXCEPTION 'INVALID_DISCOUNT'; END IF;

    INSERT INTO sale_details(venta_id,producto_id,cantidad,precio_unitario,costo_unitario,descuento,subtotal)
    VALUES(v_sale_id,v_product_id,v_qty,v_price,v_cost,v_desc,v_line);

    UPDATE inventory SET stock_actual=stock_actual-v_qty,updated_at=now() WHERE producto_id=v_product_id;
    INSERT INTO inventory_movements(producto_id,tipo,cantidad,stock_anterior,stock_nuevo,referencia_id,usuario_id)
    VALUES(v_product_id,'VENTA',-v_qty,v_stock,v_stock-v_qty,v_sale_id,p_user);

    v_subtotal := v_subtotal + v_line;
  END LOOP;

  SELECT coalesce(sum((x->>'monto')::numeric),0) INTO v_paid FROM jsonb_array_elements(p_payments) x;
  IF v_paid < v_subtotal THEN RAISE EXCEPTION 'PAYMENT_INSUFFICIENT'; END IF;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_payments) LOOP
    INSERT INTO sale_payments(venta_id,metodo,monto,referencia)
    VALUES(v_sale_id,(v_item->>'metodo')::payment_method_test,(v_item->>'monto')::numeric,v_item->>'referencia');
  END LOOP;

  UPDATE sales SET subtotal=v_subtotal,total=v_subtotal,estado='PAGADA' WHERE id=v_sale_id;
  RETURN v_sale_id;
END;
$$;

CREATE OR REPLACE FUNCTION create_pos_sale_idempotent_test(
  p_user uuid,
  p_items jsonb,
  p_payments jsonb,
  p_client_request_id uuid
) RETURNS bigint
LANGUAGE plpgsql
AS $$
DECLARE
  v_existing bigint;
  v_new bigint;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(p_client_request_id::text,0));
  SELECT id INTO v_existing FROM sales WHERE client_request_id=p_client_request_id;
  IF v_existing IS NOT NULL THEN RETURN v_existing; END IF;

  v_new := create_pos_sale_test(p_user,p_items,p_payments);
  UPDATE sales SET client_request_id=p_client_request_id WHERE id=v_new;
  RETURN v_new;
END;
$$;

INSERT INTO products(id,nombre,precio_venta,costo) VALUES
  (1,'TEST-STOCK-1',100,50),
  (2,'TEST-STOCK-2',25,10);
INSERT INTO inventory(producto_id,stock_actual) VALUES
  (1,1),
  (2,1);

COMMIT;
